"""Dedicated HNL hadronic currents, generated by the persistent exhad run server.

The router supplies each event's hadronic invariant mass W; the host keeps the
HNL widths and the lepton kinematics.  Events are rest-frame lists of
(pdg, px, py, pz, E) in the tau^- charge convention (CC hadronic charge -1).

* CC_ud, W <= 1.65 GeV: tau-data injection below 1 GeV; above, the calibrated
  string (anchor theta(W), vector/axial weights, tau-data injection, morph).
* NC light, W <= 3 GeV: injection below 1 GeV; above, a category drawn from the
  light-current composition and realized by Pythia conditioned on that category.
* NC strange: KK / K*K injection; the strange-current remainder is a phi/f1s string
  conditioned on the states outside every named channel.
* CC_us, every W: tau-normalized Breit-Wigner resonance injection.
* Fixed-edge categories for the CC_ud window and the portable boundary families.

Worker masses are 25-MeV bins (nearest for CC_ud and NC, downward for CC_us,
downward from the edge for boundary categories); the caller dilates every
event to its exact W.
"""
import atexit
import bisect
import csv
import json
import os
from functools import lru_cache
from pathlib import Path
import numpy as np
from .. import DATA, ROOT
from ..core.event_worker import WorkerPool, WorkerProcess
from ..hnl import THRESHOLDS
from ..models import CHARGED_CURRENT_SOURCE, NEUTRAL_CURRENT_SOURCE, PARENT_SPIN_WORD

EXHAD = ROOT / 'cpp' / 'exhad'
RUN_SERVERS = WorkerPool(2)  # one `exhad --runs` process per binary and XML tree
atexit.register(RUN_SERVERS.close)


def _xmldoc():
    """Pythia XML of the exhad build: EXHAD_PYTHIA8DATA first, then the make-time record."""
    explicit = os.environ.get('EXHAD_PYTHIA8DATA', '').strip()
    if explicit:
        return os.path.abspath(os.path.expanduser(explicit))
    with open(ROOT / 'cpp' / '.pythia8-build', encoding='utf-8') as stream:
        return dict(line.strip().split('=', 1) for line in stream if '=' in line)['xmldoc']


XMLDOC = _xmldoc()
EDGES = {'CC_ud': 1.65, 'NC_ud': 3.0, 'NC_s': 3.0}  # ends of the dedicated tables
# theta name -> (Pythia setting, Pythia default); cAx (axial weight) is not a setting and stays frozen
PYTHIA = {'stopNewFlav': ('StringFragmentation:stopNewFlav', 2.0), 'stopMass': ('StringFragmentation:stopMass', 0.8),
          'stopSmear': ('StringFragmentation:stopSmear', 0.2), 'probStoUD': ('StringFlav:probStoUD', 0.217),
          'mesonUDvector': ('StringFlav:mesonUDvector', 0.50), 'mesonSvector': ('StringFlav:mesonSvector', 0.55),
          'etaSup': ('StringFlav:etaSup', 0.60), 'aLund': ('StringZ:aLund', 0.68), 'bLund': ('StringZ:bLund', 0.98),
          'sigmaPT': ('StringPT:sigma', 0.335)}
# CC_ud response categories and the tau-data channels they sum (order is the release order)
CC_CATEGORIES = {'two-pion': ('pi-_pi0',), 'three-pion': ('pi-_2pi0', '2pi-_pi+'),
                 'four-pion': ('2pi-_pi+_pi0', 'pi-_3pi0'), 'five-plus': ('5pi',), 'kaon-pair': ('K_K',),
                 'kaon-pair-pion': ('K_K_pi',), 'eta-pion-pion': ('eta_pi-_pi0',),
                 'nucleon-pair': (), 'remaining': ('other',)}  # NNbar is closed at the 1.65 GeV edge


@lru_cache(maxsize=None)
def _table(name):
    """data/hnl CSV as (masses, {column: values})."""
    with open(DATA / 'hnl' / name, newline='') as stream:
        header, *rows = list(csv.reader(stream))
    return [float(row[0]) for row in rows], {h: [float(row[j]) for row in rows] for j, h in enumerate(header)}


@lru_cache(maxsize=None)
def _json(name):
    with open(DATA / 'hnl' / name) as stream:
        return json.load(stream)


def _interp(grid, values, m, scan=False):
    """Clamped linear interpolation; scan=True uses the (dv*dm)/span operation order of the calibrated targets and weights, otherwise dv*(dm/span)."""

    if m <= grid[0]:
        return values[0]

    if m >= grid[-1]:
        return values[-1]
    i = bisect.bisect_left(grid, m)
    dv, dm, span = values[i] - values[i - 1], m - grid[i - 1], grid[i] - grid[i - 1]

    return values[i - 1] + (dv * dm / span if scan else dv * (dm / span))


def _smoothstep(t):
    t = min(max(t, 0.0), 1.0)
    return t * t * (3.0 - 2.0 * t)


@lru_cache(maxsize=2)
def _anchors(kind):
    prefix = 'cc' if kind == 'HNL' else 'nc'
    cards = [_json(f'string_anchors/{prefix}_{m}.json') for m in ('1.00', '1.10', '1.20', '1.30', '1.40', '1.50', '1.60', '1.65')]
    return [(card['mass'], card['theta']) for card in cards]


def _theta(kind, m):
    """Anchor theta interpolated in W; above the last anchor relaxed to the Pythia defaults by 3.5 GeV."""
    anchors = _anchors(kind)
    (m_lo, low), (m_hi, high) = anchors[0], anchors[-1]

    if m <= m_lo:
        return dict(low)

    for (m0, t0), (m1, t1) in zip(anchors, anchors[1:]):
        if m0 <= m <= m1:
            x = (m - m0) / (m1 - m0)
            return {k: t0[k] + (t1[k] - t0[k]) * x for k in low}
    s = _smoothstep((3.5 - m) / (3.5 - m_hi))

    return {k: d + (high[k] - d) * s for k in low for d in (PYTHIA.get(k, (None, high[k]))[1],)}


@lru_cache(maxsize=2)
def _channels(kind):
    """Channel basis rows (name, 'id:count ...') in file order."""
    with open(DATA / 'hnl' / ('cc_channel_basis.txt' if kind == 'HNL' else 'nc_channel_basis.txt')) as stream:
        return tuple((parts[0], ' '.join(parts[1:])) for line in stream if len(parts := line.split('#')[0].split()) > 1)


def _lines(modes, fmt='%.17g', scale=1.0):
    """Injection-table rows 'probability ids...'."""
    return ['%s %s\n' % (fmt % (float(mode[-1]) * scale), ' '.join(str(int(pdg)) for pdg in mode[:-1]))
            for mode in modes]


def _morph(kind, weight):
    """Morph rows 'weight id:count ...' over the channel basis; the bare row weighs every other state."""
    return ['%.17g %s\n' % (weight(name), ids) for name, ids in _channels(kind)] + ['%.17g\n' % weight('other')]


def _forced(kind, channels):
    """Morph table that keeps only the given channel classes."""
    return _morph(kind, lambda name: 1.0 if name in channels else 0.0)


def _run(kind, W, n, seed, weights, *, mass='%.17g', sets=(), inject=(), morph=(), binary=None, xmldoc=None):
    """One run of n accepted events at W; weights, settings and tables travel with the request."""
    value = int(seed)  # the C++ seed is an int and the channel decayer adds 54321
    seed = value if 1 <= value <= 899_945_679 else value % 899_945_679 or 1
    paths = tuple(str(Path(path).resolve()) for path in (binary or EXHAD, xmldoc or XMLDOC))
    events = []

    # The current's quantum numbers travel, never its name; a current averages the
    # parent polarization instead of carrying its spin.
    source = CHARGED_CURRENT_SOURCE if kind == 'HNL' else NEUTRAL_CURRENT_SOURCE

    with RUN_SERVERS.use(paths, lambda: WorkerProcess(*paths, '--runs')) as server:
        server.send(f'RUN {" ".join(source.arguments)} {PARENT_SPIN_WORD[False]} {n} {seed} {mass % W} '
                    f'{weights} {len(sets)} {len(inject)} {len(morph)}\n'
                    + ''.join((*sets, *inject, *morph)))
        while not (line := server.line(None, 'dedicated run')).startswith('END'):
            if line.startswith('Fatal'):
                raise RuntimeError(f'exhad {kind} failed at W={W:.6g}: {line}')
            if line == 'E':
                events.append([])
            else:
                fields = line.split()
                events[-1].append((int(fields[0]), *map(float, fields[1:])))

    return events


CONTINUATION_RUNS = 1000  # fresh-seed runs allowed to complete one starved request


def _complete(generate, n, seed, what):
    """generate(n, seed); a run short of n (attempt budget) is continued by independent runs generate(missing,
    seed_k), seed_k derived from (seed, k), never by repeated or substituted events. Unstarved: one unchanged run."""
    events, k = generate(n, seed), 0

    while len(events) < n:
        if k == CONTINUATION_RUNS:
            raise RuntimeError('%s returned %d/%d events after %d continuation runs' % (what, len(events), n, k))
        k += 1
        state = np.random.SeedSequence([int(seed) % (1 << 64), k, 0x434F4E54]).generate_state(1, dtype=np.uint64)[0]
        events += generate(n - len(events), 1 + int(state % 899_900_000))

    return events


def _string(kind, W, n, seed, morph, inject=(), mass='%g', strange=False):
    """Calibrated string: theta(W) settings and component weights (CC vec/ax, NC rho/omega/a1 or phi/f1s)."""
    theta = _theta(kind, W)
    masses, columns = _table('cc_component_weights.csv' if kind == 'HNL' else 'nc_component_weights.csv')
    w = {c: _interp(masses, values, min(W, 1.65 if kind == 'HNL' else 3.0), scan=True) for c, values in columns.items()}
    weights = ('%.17g,%.17g' % (w['wVec'], w['wAx'] * theta['cAx']) if kind == 'HNL' else
               '0,0,%.17g,0,%.17g' % (w['wphi'], w['wf1s']) if strange else  # cAx is the isovector-axial weight only
               '%.17g,%.17g,0,%.17g,0' % (w['wrho'], w['womega'], w['wa1'] * theta['cAx']))
    sets = ['%s=%.17g\n' % (PYTHIA[k][0], v) for k, v in sorted(theta.items()) if k != 'cAx']

    return _run(kind, W, n, seed, weights, mass=mass, sets=sets, inject=inject, morph=morph)


def _cc_ud(W, n, seed):
    if W < 1.0:  # inject-only tau-data composition
        masses, columns = _table('cc_channel_fractions.csv')
        p = {c: _interp(masses, values, W) for c, values in columns.items()}
        p_eta = p['eta_pi-_pi0'] if W >= 0.54786 + 0.13957 + 0.13498 else 0.0
        p_kk = p['K_K'] if W >= 0.994 else 0.0
        p_a, p_b = p['2pi-_pi+'], p['pi-_2pi0']
        p_a += max(0.0, 1.0 - p['pi-_pi0'] - p_a - p_b - p_eta - p_kk)  # 4pi and closed modes fold into 3pi
        modes = [(-211, 111, p['pi-_pi0'])]
        modes += [(113, -211, p_a), (-213, 111, p_b)] if W >= 0.95 else [(211, -211, -211, p_a), (-211, 111, 111, p_b)]
        if p_eta > 0.0:
            modes.append((221, -213, p_eta) if W >= 1.324 else (221, -211, 111, p_eta))
        if p_kk > 0.0:
            modes.append((-321, 311, p_kk))
        inject = _lines([(*mode[:-1], mode[-1] * (1.0 - 1e-6)) for mode in modes if mode[-1] > 1e-6], '%.8f')
        generate = lambda k, s: _run('HNL', W, k, s, '1,1', inject=inject)
    else:
        masses, columns = _table('cc_injection_fractions.csv')
        injected, table = [], []
        for label in list(columns)[1:]:
            p = _interp(masses, columns[label], W)
            if W < {'pi-_3pi0': 1.046, 'K_K_pi': 1.40}.get(label, 0.0) or p <= 1e-6:
                continue
            injected.append(label)
            modes = ([(221, -211, 111, 1.0)] if label == 'eta_pi-_pi0' and W < 1.324
                     else _json('cc_injection_modes.json')[label])
            table += [(*map(int, mode[:-1]), p * float(mode[-1])) for mode in modes]
        card, (masses, targets) = _json('cc_string_morph.json'), _table('cc_string_targets.csv')
        morph = {}
        for c in {*(name for name, _ in _channels('HNL')), 'other'}:  # data / string prediction, capped at 15
            d = _interp(masses, targets[c], W, scan=True)  # unpopulated channels: 0 if data > 1e-4
            p = _interp(card['m'], card['pred'][c], W) if c in card['pred'] else 0.0
            morph[c] = (0.0 if d > 1e-4 else 1.0) if p <= 0.0 else min(max(d / p, 0.0), 15.0)
        morph.update(dict.fromkeys(injected, 0.0))
        rows, inject = _morph('HNL', morph.get), _lines(table)
        generate = lambda k, s: _string('HNL', W, k, s, rows, inject)

    return _complete(generate, n, seed, 'CC_ud at W=%.6g' % W)


def _nc_inject(modes, W, n, seed, binary=None, xmldoc=None):
    total = sum(mode[-1] for mode in modes)  # keep the %.8f table strictly below unit sum
    scale = (1.0 - 1e-6) / total if total > 1.0 - 1e-6 else 1.0
    return _run('HNL_NC', W, n, seed, '1,1,1,1,1', inject=_lines(modes, '%.8f', scale), binary=binary, xmldoc=xmldoc)


def _nc_light(W, n, seed):
    """Draw categories from the light-current composition, then realize each with Pythia conditioned on it."""
    masses, columns = _table('nc_ud_channel_fractions.csv')  # rho, omega, a1 components and their own remainder
    p = {c: _interp(masses, columns[c], W) for c in ('2Pich', '3Pi', '4Pi', '5Pi', 'other')}
    # Only 5Pi + other is identified; Pythia splits that aggregate event by event.
    target = {'2Pich': p['2Pich'], '3Pi': p['3Pi'], '4Pi': p['4Pi'], '5Pi': 0.0, 'other': p['5Pi'] + p['other']}
    total = sum(target.values())

    if not np.isfinite(total) or abs(total - 1.0) > 2.0e-8 or min(target.values()) < 0.0:
        raise RuntimeError('light-NC category measure does not close at W=%.6g' % W)
    target['other'] += 1.0 - total
    rng = np.random.default_rng(seed)
    events = []
    counts = rng.multinomial(n, np.asarray(list(target.values()), float))

    for index, (category, count) in enumerate(zip(target, counts)):
        count, category_seed = int(count), seed + 1009 * (index + 1)
        if count <= 0:
            continue
        if category == '2Pich':
            generate = lambda k, s: _nc_inject([(211, -211, 1.0 - 1e-6)], W, k, s)
        elif category == 'other':
            generate = lambda k, s: _string('HNL_NC', W, k, s, _forced('HNL_NC', {'5Pi', 'other'}), mass='%.17g')
        else:
            generate = lambda k, s: _string('HNL_NC', W, k, s, _forced('HNL_NC', {category}))
        events.extend(_complete(generate, count, category_seed, 'light-NC category %s at W=%.6g' % (category, W)))
    rng.shuffle(events)

    return events


def _nc_strange(W, n, seed):
    """Strange-current composition, generated above the K Kbar floor: KK and KKpi (from 1.40 GeV) injected; the
    remainder is a phi/f1s string with every named channel excluded, drawn in the same run."""
    masses, columns = _table('nc_s_channel_fractions.csv')  # phi, f1s components and their own remainder
    p = {label: value for label in ('KK', 'KKpi', 'other')
         if W >= (1.40 if label == 'KKpi' else 0.0) and (value := _interp(masses, columns[label], W)) > 1e-6}
    total = sum(p.values())
    modes = [(int(i1), int(i2), p[label] / total * frac) for label in ('KK', 'KKpi') if label in p
             for i1, i2, frac in _json('nc_injection_modes.json')[label]] or [(321, -321, 1.0 - 1e-6)]
    W = max(W, 2 * 0.496 + 1e-3)

    if 'other' not in p:
        return _nc_inject(modes, W, n, seed)

    return _string('HNL_NC', W, n, seed, _forced('HNL_NC', {'other'}), _lines(modes, '%.8f'), '%.17g', strange=True)


def _nc(W, n, seed, flavor):
    if flavor == 'strange':
        generate = lambda k, s: _nc_strange(W, k, s)
    elif W < 1.0:  # the 0.275-GeV bin lies below pi+ pi-, the only open state up to 0.4 GeV: generated at 0.2801 GeV
        masses, columns = _table('nc_ud_channel_fractions.csv')
        p2, p3 = _interp(masses, columns['2Pich'], W), _interp(masses, columns['3Pi'], W)
        p3 += max(0.0, 1.0 - p2 - p3)  # 4pi, 5pi and other fold into 3pi
        modes = [(211, -211, p2)] if p2 > 1e-6 else []
        if p3 > 1e-6:
            modes += [(113, 111, 0.5 * p3), (213, -211, 0.25 * p3), (-213, 211, 0.25 * p3)] if W >= 0.95 else [(211, -211, 111, p3)]
        modes = [(*mode[:-1], mode[-1] * (1.0 - 1e-6)) for mode in modes if mode[-1] > 1e-6]
        generate = lambda k, s: _nc_inject(modes, W if W >= THRESHOLDS['NC_ud'] else 0.2801, k, s)
    else:
        generate = lambda k, s: _nc_light(W, k, s)

    return _complete(lambda k, s: [event for event in generate(k, s) if all(p[4] > 0.0 for p in event)],
                     n, seed, 'exhad NC (%s) at W=%.6g' % (flavor, W))


# CC_us: parent -> ((daughters, isospin fraction, orbital L), ...); hadronic charge -1, strangeness -1
US_MODES = {'Kstar892': (((-321, 111), 1.0 / 3.0, 1), ((-311, -211), 2.0 / 3.0, 1)),
            'K1_1270': (((-321, 113), 1.0 / 6.0, 0), ((-311, -213), 1.0 / 3.0, 0),
                        ((-323, 111), 1.0 / 6.0, 0), ((-313, -211), 1.0 / 3.0, 0)),
            'K1_1400': (((-323, 111), 1.0 / 3.0, 0), ((-313, -211), 2.0 / 3.0, 0)),
            'Kstar1410': (((-323, 111), 1.0 / 3.0, 1), ((-313, -211), 2.0 / 3.0, 1)),
            'K_eta': (((-321, 221), 1.0, 1),)}
US_MASS = {111: 0.13498, 211: 0.13957, 221: 0.54785, 311: 0.49761, 321: 0.49368,
           113: 0.77549, 213: 0.77549, 313: 0.89555, 323: 0.89167}
US_MIN_W = min(sum(US_MASS[abs(p)] for p in ids) for modes in US_MODES.values() for ids, _, _ in modes)
M_TAU = 1.77686


def _q(W, ids):
    """Two-body rest-frame momentum (scalar or array W)."""
    W = np.asarray(W, dtype=float)
    m1, m2 = (US_MASS[abs(int(p))] for p in ids)
    return np.sqrt(np.maximum((W * W - (m1 + m2) ** 2) * (W * W - (m1 - m2) ** 2), 0.0)) / (2.0 * np.maximum(W, 1e-300))


def _shape(name, W):
    """Relativistic Breit-Wigner, running width Gamma0 (sum_f q^(2L+1))/(same at the pole) M/W."""
    record = _json('cc_us_resonances.json')[name]  # the explicit K pole is EventCalc's N -> l K
    mass, width = float(record['mass']), float(record['width'])
    W = np.asarray(W, dtype=float)
    phase_sum = lambda x: sum(f * _q(x, ids) ** (2 * L + 1) for ids, f, L in US_MODES[name])
    phase = phase_sum(W)
    gamma = width * (phase / float(phase_sum(mass))) * (mass / np.maximum(W, 1e-300))
    denominator = (W * W - mass ** 2) ** 2 + (mass * gamma) ** 2

    return np.where(phase > 0.0, mass * gamma / np.maximum(denominator, 1e-300), 0.0)


@lru_cache(maxsize=None)
def _us_norm(name):
    """Integral under the tau J=1 kernel 2W (1-x)^2 (1+2x); each source br_tau is that integral."""
    grid = np.linspace(US_MIN_W, M_TAU, 12000)
    x = (grid / M_TAU) ** 2
    kernel = np.where((grid > 0.0) & (grid < M_TAU), 2.0 * grid * (1.0 - x) ** 2 * (1.0 + 2.0 * x), 0.0)
    return float(np.trapezoid(kernel * _shape(name, grid), grid))


def _cc_us(W, n, seed):
    if not W > US_MIN_W:
        raise ValueError('CC-us continuum requires W > %.8g GeV; got %r' % (US_MIN_W, W))
    weighted = {}

    for name, modes in US_MODES.items():
        strength = float(_json('cc_us_resonances.json')[name]['br_tau']) * float(_shape(name, W)) / _us_norm(name)
        if strength <= 0.0:
            continue
        open_modes = [(ids, value) for ids, f, L in modes
                      if (value := f * float(_q(W, ids)) ** (2 * L + 1)) > 0.0 and sum(US_MASS[abs(p)] for p in ids) <= W]
        subtotal = sum(value for _, value in open_modes)
        for ids, value in open_modes if subtotal > 0.0 else ():
            weighted[ids] = weighted.get(ids, 0.0) + strength * value / subtotal
    total, running, table = sum(weighted.values()), 0.0, []

    for index, (ids, value) in enumerate(weighted.items()):
        p = value / total if index + 1 < len(weighted) else 1.0 - running  # exact unit sum
        running += p
        table.append((*ids, p))
    inject = _lines(table)
    events = _complete(lambda k, s: _run('HNL', W, k, s, '1,1', inject=inject), n, seed, 'exhad CC-us at W=%.6g' % W)

    if any(not event or any(not all(np.isfinite(v) for v in p[1:]) or p[4] <= 0.0 for p in event) for event in events):
        raise RuntimeError('exhad CC-us generation returned an invalid event at W=%.6g' % W)

    return events


def decays_at_W(current, W_values, seed, exact=False):
    """Events at each W, generated per worker bin (seed + bin index), or at exact W."""
    W = np.asarray(W_values, float)

    if current == 'CC_us':  # downward bins, coarse above 1.65 GeV, so every state is open at W
        bins = np.where(W <= 1.65 + 1e-12, np.floor(W / 0.025 + 1e-12) * 0.025,
                        1.65 + np.floor((W - 1.65) / 0.25 + 1e-12) * 0.25)
        bins = np.minimum(np.where(bins <= US_MIN_W, W, bins), W)
    else:
        if np.max(W) > EDGES[current] + 1e-9:
            raise ValueError('%s dedicated tables end at W=%g GeV' % (current, EDGES[current]))
        bins = np.round(np.round(W / 0.025) * 0.025, 5)

    if exact:
        bins = W.copy()
    backend = {'CC_ud': _cc_ud, 'CC_us': _cc_us,
               'NC_ud': lambda *a: _nc(*a, 'light'), 'NC_s': lambda *a: _nc(*a, 'strange')}[current]
    out = [None] * len(W)

    for k, Wc in enumerate(np.unique(bins)):
        indices = np.flatnonzero(bins == Wc)
        for index, event in zip(indices, backend(float(Wc), len(indices), seed + k)):
            out[index] = event

    return out


def boundary_categories(current, categories, W_values, seed, exact=False, binary=None, xmldoc=None):
    """Fixed-edge categories (CC_ud at 1.65 GeV; NC_ud two-pion at 3.0 GeV) generated below each W."""
    edge = EDGES[current]

    if current == 'CC_ud':  # keep the measured charge split inside each category
        masses, columns = _table('cc_channel_fractions.csv')
        rng, labels = np.random.default_rng(seed), []
        for category in categories:
            options = CC_CATEGORIES[category]
            weights = np.asarray([columns[label][-1] for label in options], float)
            if weights.sum() <= 0.0:
                raise RuntimeError('conditioned CC category has zero boundary support: ' + category)
            labels.append(options[int(rng.choice(len(options), p=weights / float(weights.sum())))])
    else:
        labels = [{'two-pion': '2Pich'}[category] for category in categories]
    worker_W = [w if exact else min(w, edge + 0.025 * int(np.floor((w - edge) / 0.025 + 1e-12))) for w in W_values]
    events = [None] * len(labels)

    for group, key in enumerate(sorted(set(zip(labels, worker_W)))):
        (label, W), indices = key, [i for i, item in enumerate(zip(labels, worker_W)) if item == key]
        group_seed = seed + 1009 * (group + 1)
        if current == 'NC_ud':
            generate = lambda k, s: _nc_inject([(211, -211, 1.0 - 1e-6)], W, k, s, binary, xmldoc)
        elif label in _json('cc_injection_modes.json'):
            modes = _json('cc_injection_modes.json')[label]
            inject = _lines(modes, scale=(1.0 - 1.0e-6) / sum(float(mode[-1]) for mode in modes))
            generate = lambda k, s: _run('HNL', W, k, s, '1,1', binary=binary, xmldoc=xmldoc, inject=inject)
        else:
            generate = lambda k, s: _string('HNL', W, k, s, _forced('HNL', {label}))
        generated = _complete(generate, len(indices), group_seed, 'conditioned %s %s at W=%.6g' % (current, label, W))
        for index, event in zip(indices, generated):
            events[index] = event

    return events
